name: Terraform Lint and Validate on PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: '1.12.2'

      - name: Terraform Init
        run: terraform init

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate
